# Уникальное имя приложения на Fly.io
app = "simplex-server"

# Параметры сборки
[build]
  dockerfile = "Dockerfile"

# Настройка служб
[[services]]
  internal_port = 5222
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 5222
