app = "jami-bootstrap"
primary_region = "fra" # или другой ближайший регион
[build]
  dockerfile = "./Dockerfile"

[[services]]
  internal_port = 4222
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443
